# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    mail:
        from: SoruMania@localhost
    security:
        authentication:
            oauth:
                clientid: SoruManiaapp
                secret: mySecretOAuthSecret
                # Token is valid 30 minutes
                tokenValidityInSeconds: 1800
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: cade0f0c9eb96b3a41b8761d6e7308c18ade1915
    swagger:
        title: SoruMania API
        description: SoruMania API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
